
from typing import Dict
from pathlib import Path
import json
import datetime

HTML_TEMPLATE = """<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>PII Redactor Report</title>
    <style>
      body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 2rem; }
      h1, h2 { margin: 0.2rem 0; }
      table { border-collapse: collapse; width: 100%; margin-top: 1rem; }
      th, td { border: 1px solid #ccc; padding: 0.5rem; text-align: left; }
      th { background: #fafafa; }
      .pill { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 0.5rem; background: #efefef; margin-right: 0.25rem; }
      .small { color: #666; font-size: 0.9rem; }
      footer { margin-top: 3rem; color: #666; font-size: 0.8rem; }
    </style>
  </head>
  <body>
    <h1>PII Redactor Lite — Report</h1>
    <div class="small">Generated: {generated}</div>
    <h2>Summary</h2>
    <div>
      {summary_pills}
    </div>
    <table>
      <thead>
        <tr><th>File</th><th>Output</th><th>Total Findings</th><th>By Type</th></tr>
      </thead>
      <tbody>
        {rows}
      </tbody>
    </table>
    <footer>
      <p>This report was generated by PII Redactor Lite. Findings are approximate and pattern-based; manual review recommended.</p>
    </footer>
  </body>
</html>"""

def render_html_report(report: Dict, out_path: Path):
    out_path = Path(out_path)
    # build pills
    pills = []
    for k, v in sorted(report.get("summary", {}).items()):
        pills.append(f"<span class='pill'><strong>{k}</strong>: {v}</span>")
    rows = []
    for fr in report.get("files", []):
        counts = ", ".join([f"{k}:{v}" for k, v in sorted(fr.get('counts', {}).items())]) or "-"
        rows.append(
            "<tr>" +
            f"<td>{fr['file']}</td><td>{fr['out_file']}</td><td>{fr['total_findings']}</td><td>{counts}</td>" +
            "</tr>"
        )
    html = HTML_TEMPLATE.format(
        generated=str(datetime.datetime.utcnow()) + " UTC",
        summary_pills=" ".join(pills) or "<em>No findings</em>",
        rows="\n".join(rows) or "<tr><td colspan='4'><em>No files processed.</em></td></tr>"
    )
    out_path.write_text(html, encoding="utf-8")

def write_json_report(report: Dict, out_path: Path):
    out_path = Path(out_path)
    out_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
